# Generated by Django 4.2 on 2023-05-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo')),
                ('data', models.DateField(verbose_name='data')),
                ('local', models.CharField(max_length=50, verbose_name='local')),
                ('tarefa', models.CharField(max_length=200, verbose_name='tarefa')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
            ],
        ),
    ]
